server:
  port: ${PORT:8082}

spring:
  application:
    name: 'project-101.back.java'

app-config:
  name: ${APP_NAME:Project 101}
  description: ${APP_DESCRIPTION:Projeto backend somo para estudos.}
  version: ${APP_VERSION:1.0.0}
  url: ${APP_URL:http://localhost:8082}
